name: Assignment 5

on: [push] 

jobs:
  Assignment5:
    runs-on: windows-latest

    steps:
      - name: Checkout Repostiory 
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
   
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run app
        working-directory: ./
        run: python main.py

      - name: run tests
        working-directory: ./
        run: locust -f Assignment5.py --headless -u 1 -r 1 --host http://localhost:9000 --run-time 1m --html=locustreport.html

      - name: Archive capacity test report
        uses: actions/upload-artifact@v3
        with:
         name: capacitytestreport
         path: locustreport.html
